version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  lint-dockerfile:
    jobs:
      - lint

      build:
        working_directory: /docker-monitor
        docker:
          - image: docker:19.03.13-ce-git
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Install dependencies
              command: |
                apk add --no-cache py-pip=9.0.0-r1
                pip install docker-compose==1.25.0
          - run:
              name: Run tests
              command: |
                bash run.sh
          # - deploy:
          #     name: Push application Docker image
          #     command: |
          #       docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
          #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp1:$CIRCLE_SHA1
          #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp1:latest
          #       docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
          #       docker push $DOCKER_HUB_USER_ID/dockerapp1:latest
    